server:
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "hr-app-db"
  sslmode: "disable"

jwt:
  secret: "secretkey"
  expiration_hours: 1
